version: '3.5'

services:
  ce226:
    image: dinhtp/php:7.1.33-composer1.10.22
    restart: always
    volumes:
      - ./ce226:/var/www/html
    ports:
      - 7010:80
    depends_on:
      - ce-mariadb
    links:
      - ce-mariadb
    hostname: ce226
    container_name: ce226
    networks:
      - ce-network

  ce234:
    image: dinhtp/php:7.2.34-composer1.10.22
    restart: always
    volumes:
      - ./ce234:/var/www/html
    ports:
      - 7015:80
    depends_on:
      - ce-mariadb
    links:
      - ce-mariadb
    hostname: ce234
    container_name: ce234
    networks:
      - ce-network

  ce236:
    image: dinhtp/php:7.3.28-composer1.10.22
    restart: always
    volumes:
      - ./ce236:/var/www/html
    ports:
      - 7020:80
    depends_on:
      - ce-mariadb
    links:
      - ce-mariadb
    hostname: ce236
    container_name: ce236
    networks:
      - ce-network

  ce241:
    image: dinhtp/php:7.4.19-composer1.10.22
    restart: always
    volumes:
      - ./ce241:/var/www/html
    ports:
      - 7025:80
    depends_on:
      - ce-mariadb
    links:
      - ce-mariadb
    hostname: ce241
    container_name: ce241
    networks:
      - ce-network
          
  ce242:
    image: dinhtp/php:7.4.19-composer2.0.14
    restart: always
    volumes:
      - ./ce242:/var/www/html
    ports:
      - 7030:80
    depends_on:
      - ce-mariadb
    links:
      - ce-mariadb
    hostname: ce242
    container_name: ce242
    networks:
      - ce-network

  # Elastic Search Services
  # Execute the following command to increase max virtual memory
  # sudo sysctl -w vm.max_map_count=262144
  ce-est-241:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    volumes:
      - ce-est-241:/usr/share/elasticsearch/data
    environment:
      - node.name=ce-est-241
      - cluster.name=ce-est-cluster
      - discovery.seed_hosts=ce-est-241
      - cluster.initial_master_nodes=ce-est-241
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9241:9200
    container_name: ce-est-241
    networks:
      - ce-network

  ce-est-242:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    volumes:
      - ce-est-242:/usr/share/elasticsearch/data
    environment:
      - node.name=ce-est-242
      - cluster.name=ce-est-cluster
      - discovery.seed_hosts=ce-est-242
      - cluster.initial_master_nodes=ce-est-242
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9242:9200
    container_name: ce-est-242
    networks:
      - ce-network

  # Infrastructure Services
  ce-mariadb:
    image: mariadb
    ports:
     - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ce-mariadb-data:/var/lib/mysql
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: ce-mariadb
    networks:
      - ce-network

  ce-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
     - 8080:80
    environment:
     - PMA_HOST=ce-mariadb
     - PMA_USER=root
     - PMA_PASSWORD=root
     - MYSQL_ROOT_PASSWORD=root
    hostname: ce-phpmyadmin
    container_name: ce-phpmyadmin
    networks:
      - ce-network

  ce-nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    expose:
      - '80'
      - '443'
    container_name: ce-nginx
    networks:
      - ce-network

  ce-mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    hostname: ce-mailhog
    container_name: ce-mailhog
    networks:
      - ce-network

networks:
  ce-network:
    driver: bridge

volumes:
  ce-mariadb-data:
    driver: local
  ce-est-241:
    driver: local
  ce-est-242:
    driver: local
  
