version: '3.5'

services:
  # ce226:
  #   image: dinhtp/php:7.1.33-composer1.10.22
  #   restart: always
  #   volumes:
  #     - ./ce226:/var/www/html
  #   ports:
  #     - 8010:80
  #   depends_on:
  #     - mariadb
  #   links:
  #     - mariadb
  #   hostname: magento-ce226
  #   container_name: magento-ce226
  #   networks:
  #     - magento2-ce

  mariadb:
    image: mariadb
    ports:
     - 3300:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mariadb/data:/var/lib/mysql
      - ./mariadb/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - magento2-ce

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
     - 8080:80
    environment:
     - PMA_HOST=mariadb
     - PMA_USER=root
     - PMA_PASSWORD=root
     - MYSQL_ROOT_PASSWORD=root
    hostname: magento-phpmyadmin
    container_name: magento-phpmyadmin
    networks:
      - magento2-ce

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    expose:
      - '80'
      - '443'
    hostname: magento-nginx
    container_name: magento-nginx
    networks:
      - magento2-ce

networks:
  magento2-ce:
    driver: bridge
